name: Build Flutter Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.x'

      - name: Install Dependencies
        run: flutter pub get

      - name: Enable Windows Build
        run: flutter config --enable-windows-desktop

      - name: Build Windows
        run: flutter build windows --release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: build/windows/runner/Release/
